include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "lint_docker.yaml"
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "build_docker.yaml"
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "security_scan.yaml"

variables:
  IMAGE: "tulibraries/tupress"
  VERSION: "${DOCKER_IMAGE_VERSION}-${CI_BUILD_ID}"
  BUILD_PATH: ".docker/app/"

stages:
  - lint
  - build
  - scan

lint:
  extends: .lint_docker

build:
  stage: build
  extends: .build_image

scan:
  stage: scan
  extends: .scanimage
