include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "lint_docker.yaml"
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "build_docker.yaml"
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "security_scan.yaml"

variables:
  IMAGE: "tulibraries/tupress"

before_script:
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

stages:
  - lint
  - build
  - scan
  - tag

lint:
  extends: .lint_docker
  variables:
    DF: ".docker/app/Dockerfile"

build:
  stage: build
  extends: .build_image
  variables:
    DF: ".docker/app/Dockerfile --build-arg RAILS_ENV=production --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE  --no-cache"

scan:
  stage: scan
  extends: .scanimage

tag:
  stage: tag
  extends: .tag_image
