version: "3.4"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: press_6_db
      MYSQL_ROOT_PASSWORD: press_6_ci

  test_app:
    build:
      context: .
      dockerfile: .docker/ci-app/Dockerfile.ci
    ports:
      - "3000"
    environment:
      BUNDLE_PATH: /app/vendor/bundle
      RAILS_ENV: test
      TUPRESS_DB_HOST: db
      TUPRESS_DB_NAME: press_6_db
      TUPRESS_DB_PASSWORD: press_6_ci

    entrypoint:
      - "tail"
      - "-f"
      - /dev/null
