version: 2

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v6-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v6-{{ arch }}-{{ .Branch }}
            - gem-cache-v6-{{ arch }}
            - yarn-cache-v6-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}


      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13

      - run: if [ -e /var/run/docker.sock ]; then sudo chown circleci:circleci /var/run/docker.sock; fi

      - run:
          name: remove dockerignore
          command: rm .dockerignore

      - run:
          name: Build docker containers
          command: docker-compose -p press_6 -f docker-compose.ci.yml up -d

      - run:
          name: Run bundler on the test app container
          command: |
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app bundle install --path vendor/bundle
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app bundle binstubs --all
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app bundle binstubs bundler --force

      - run:
          name: Run yarn install on the test app container
          command: |
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app yarn install --frozen-lockfile

      - save_cache:
          key: gem-cache-v6-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
              - vendor/bundle
      - save_cache:
          key: yarn-cache-v6-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
              - node_modules

      - run:
          name: Run linter
          command: |
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app bundle exec rubocop -c .rubocop.yml

      - run:
          name: Database migrations
          command: |
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app bundle exec rails db:migrate

      - run:
          name: Run ruby tests
          command: |
              docker-compose -p press_6 -f docker-compose.ci.yml exec test_app bundle exec rake spec
